### ISSUE TITLE
(1.29.1 only) !wip command doesn't work on BeatSaberPlus update 6.2.1 due to new "ChatPlexSDK_BS" name

### ISSUE THREAD

**Issue by drummerXD** [catsethecat/wipbot#6]
Issue is only relevant for game v1.29.1 (pre unity upgrade build) / mod v1.14.0

"BeatSaberPlus.dll is no more and got replaced by ChatPlexSDK_BS.dll make sure to delete the old one and to include the new one" -HardCPP

Unfortunately a side effect of that is the command no longer works.

**Comment by catsethecat** [comment]
backported mod v1.15 for bs 1.29.1 due to popular demand
https://github.com/catsethecat/wipbot/releases/tag/v1.15.0-bs1.29.1
